load("//tools/build_defs/kotlin:rules.bzl", "kt_jvm_library")

package(default_visibility = [
    "//java/com/google/android/libraries/pcc/chronicle:api_visibility",
])

kt_jvm_library(
    name = "annotation",
    srcs = glob(["*.kt"]),
    constraints = ["android"],
    deps = [],
)
