// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package com.google.android.as.oss.featurelauncher.api;


option java_package = "com.google.android.as.oss.featurelauncher.api.proto";
option java_multiple_files = true;

// Service for executing authorized features on behalf of clients
service PcsFeatureLauncherService {
  // Executes an authorized feature on behalf of a client.
  rpc ExecuteFeature(ExecuteFeatureRequest) returns (ExecuteFeatureResponse) {
    option deadline = 5.0;
  }
}

// Request message for executing features.
message ExecuteFeatureRequest {
  // The features to execute.
  repeated Feature feature = 1;
}

// Response message for executing feature requests.
message ExecuteFeatureResponse {
  // The results of the feature operations.
  repeated FeatureResult feature_result = 1
     ;
}

message Feature {
  FeatureType feature_type = 1;

  oneof params {
    RelationshipsParams relationships_params = 2
       ;
  }
}

// Supported proxy features
enum FeatureType {
  FEATURE_TYPE_UNSPECIFIED = 0;
  FEATURE_TYPE_RELATIONSHIPS_ONBOARDING_CONSENT = 1;
  FEATURE_TYPE_RELATIONSHIPS_SETTINGS = 2;
  FEATURE_TYPE_RELATIONSHIPS_REMOVE_VIP_CONFIRMATION = 3;
}

message RelationshipsParams {
  int64 contact_id = 1;
}

// Represents the result of a single feature operation.
message FeatureResult {
  // The feature that was executed.
  Feature feature = 1;

  // The status of the feature operation.
  enum Status {
    UNKNOWN = 0;
    SUCCESS = 1;
    FAILURE = 2;
  }
  Status status = 2;

  // The result code from the activity.
  int32 result_code = 3;

  // The parceled result.
  bytes parceled_result = 4;
}
