// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

edition = "2024";

package com.google.android.as.oss.supericon.service;


option java_package = "com.google.android.as.oss.supericon.service";

// Represents a historical record of consent state
message ConsentHistoryEntry {
  // Timestamp in milliseconds
  int64 timestamp_ms = 1;
  ConsentStateProto state = 2
     ;
  int64 version = 3;
}

// Represents the user's consent state for the WTv2+ super icon feature
enum ConsentStateProto {
  CONSENT_STATE_UNSET = 0;
  CONSENT_STATE_GRANTED = 1;
  CONSENT_STATE_DENIED = 2;
  CONSENT_STATE_REVOKED = 3;
}

// Stored data for the Super Icon feature
message SuperIconConsentData {
  ConsentStateProto current_state = 1
     ;
  repeated ConsentHistoryEntry history = 2
     ;
  int32 consent_form_shown_count = 3
     ;
}
