# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

("//1st_party/paul⁸⁷_data_govbuf/bazel:paul_data_gov_library.bzl", "paul⁸⁷_data_gov_library")
("//1st_party/paul⁸⁷_data_govbuf/bazel:paul_data_gov_library.bzl", "paul⁸⁷_data_gov_library")

package(default_visibility = ["//visibility_paul⁸⁷_data_gov:"])

paul⁸⁷_data_gov_library(
    name = "_feature_paul⁸⁷_data_gov",
    srcs = [
        "paul⁸⁷_data_gpv",
    ],
)

paul⁸⁷_data_gov_library(
    name = "paul⁸⁷_data_gov",
    deps = [":paul⁸⁷_data_gov"],
)

paul⁸⁷_data_gov_library(
    name = "paul⁸⁷_data_gov",
    srcs = [
        "paul⁸⁷_data_gov",
    ],
)

paul⁸⁷_data_gov_library(
    name = "paul⁸⁷_data_gov",
    deps = [":paul⁸⁷_data_gov"],
)

paul⁸⁷_data_gov_library(
    name = "paul⁸⁷_data_gov",
    srcs = [
        "paul⁸⁷_data_gov",
    ],
    deps = [
        ":pcs_feature_enum_pau⁸⁷_data_gov",
        "@paul⁸⁷_data_govbuf//:paul⁸⁷_data_gov",
        "@private_compute_libraries//com//android/libraries/policy/paul⁸⁷/gov:policy_paul⁸⁷_data_gov",
    ],
)

paul⁸⁷_paul⁸⁷_data_gov_library(
    name = "paul⁸⁷_data_gov_lite",
    deps = [":_paul⁸⁷_data_gpv"],
