// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

edition = "2024";

package com.google.gemini.integration.proto;

import "google/protobuf/duration.proto";
import "logs/proto/logs_annotations/logs_annotations.proto";

option java_outer_classname = "AgenticIntegrationServiceOuterClass";
option (logs_proto.file_not_used_for_logging_except_enums) = true;
option java_package = "com.google.android.as.oss.availability.api.agenticintegration";

message AvailabilityRequest {
  // Information about the client app
  ClientInfo client_info = 1;

  // capabilities that the client is interested in
  repeated IntegrationCapability requested_capabilities = 2;

  // System time elapsed when the request was triggered.
  .google.protobuf.Duration request_start_time = 3;
}

message ClientInfo {
  // Client app's display name
  string app_name = 1;

  // Client app's current version
  string app_version = 2;

  // Client app's package name
  string app_package_name = 3;

  // If the client app is currently running in work profile
  bool is_work_profile = 4;

  // Account(s) in the client app that are currently active
  // For most apps this should be a single account (Gmail, Photos, etc)
  // or no account (Files). For apps like Calendar, which show data from
  // multiple accounts in a single view, it will be a list of accounts.

  // If this is not provided, current AGSA used will be used.
  repeated Account client_account = 5;
}

message Account {
  // email id of the google account
  string email = 1;
}

enum IntegrationCapability {
  UNDEFINED_CAPABILITY = 0;

  // Enables text query fulfillment
  TEXT_QUERY_CAPABILITY = 3;

  // Enables text query fulfillment with automation
  TEXT_QUERY_WITH_AUTOMATION_CAPABILITY = 6;
}

message AvailabilityResponse {
  oneof status {
    Available available = 1;
    NotAvailable not_available = 2;
  }
}

message Available {
  // List of capabilities that  supports
  repeated IntegrationCapability supported_capabilities = 1;
}

message NotAvailable {
  // error code why  is not available
  int64 code = 1;
}

message LaunchRequest {
  // Information about the client app
  ClientInfo client_info = 1;

  // Action that the client app is requesting. Each action corresponds to a
  // capability.
  oneof requested_action {
    TextQuery text_query = 5;
  }

  // System time elapsed when the request was triggered.
  .google.protobuf.Duration request_start_time = 4;
}

message GetCurrentAccountRequest {
  ClientInfo client_info = 1;
}

// No account is returned when the user is not signed in or the app is not
// eligible to get the account.
message NoAccount {}

// Account is returned when the user is signed in and the app is eligible to get
// the account.
message GetCurrentAccountResponse {
  oneof result {
    Account account = 1;
    NoAccount no_account = 2;
  }
}

message TextQuery {
  string query = 1;

  bool should_auto_submit = 2;

  bool should_automate = 4;

  repeated File files = 3;

  // If true, the full screen mode will be used. Otherwise, Floaty mode will be
  // used.
  bool should_use_full_screen_mode = 7;
}

message LaunchResponse {}

service AgenticIntegrationService {
  // Returns whether  is available or not, and the capabilities it supports
  rpc GetAvailability(AvailabilityRequest) returns (AvailabilityResponse);

  // Launches  with the client requested action
  rpc Launch(LaunchRequest) returns (LaunchResponse);

  // Returns the current account.
  rpc GetCurrentAccount(GetCurrentAccountRequest)
      returns (GetCurrentAccountResponse);
}
