// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

edition = "2024";

package com.google.android.as.oss.asr.api;

import "src/com/google/android/as/oss/asr/api/srsg_feature_config.proto";

option java_outer_classname = "SrsgService";
option java_package = "com.google.android.as.oss.asr.api";

service GoogleAsrService {
  // A communication channel that establishes a connection to the recognizer and
  // directs requests to manage the recognition session, e.g. start, stop,
  // pause, resume, update configs, etc. It continuously produces recognition
  // events while the session is running.
  rpc RecognitionSession(stream RecognitionRequest)
      returns (stream RecognitionResponse) {
    option deadline = 36000;  // 10 hrs in seconds
  }
}

// Streaming recognition request action, can be one of the
// start/pause/resume/stop/etc.
message RecognitionRequest {
  message StartAction {
    // The client metadata. Besides logging, this info is also used to determine
    // what features can be enabled.
    ClientInfo client_info = 1;

    // The primary locale (in bcp-47 format, e.g. en-US) in which the speech
    // should be transcribed (ASR). Expects audio to be spoken in this locale.
    string primary_locale = 3;

    // The additional locales (in bcp-47 format, e.g. en-US) possibly involved
    // in the speech. This is only applicable in the online pipeline.
    repeated string additional_locale = 4
       ;

    // The recognizer mode indicates whether the recognition should run
    // on-device only or online as the primary.
    RecognizerMode recognizer_mode = 5;

    // The parameters needed to enable the desired features.
    FeatureConfig feature_config = 6;

    // The target locale (in bcp-47 format, e.g. en-US) in which the speech
    // should be translated (AST). Note that ASR (for transcribed text) uses
    // `primary_locale` as target language, whereas AST (for translated text)
    // uses `target_locale`. AST is enabled along with ASR when
    //   - `target_locale` is set, and
    //   - mode is `FALLBACK_ALWAYS`.
    // AST results are emitted as `EnhancedRecognitionEvent` in SODA events when
    //   - `emit_enhancement_asynchronously` is true, and
    //   - `request_soda_events` is set in `FeatureConfig`.
    string target_locale = 8;

    reserved 2, 7;
  }

  // Type of the action applied to the recognition session.
  oneof action_type {
    // An action that starts the recognition session.
    StartAction start_action = 1;
  }
}

enum RecognizerMode {
  option features.enum_type = CLOSED;

  // The default value. This value is used when the recognizer mode is not
  // specified.
  RECOGNIZER_MODE_UNSPECIFIED = 0;

  // Using OnDevice recognizer only
  RECOGNIZER_MODE_ONDEVICE_ONLY = 1;

  // Using Online recognizer with fallback to OnDevice if have network issue.
  RECOGNIZER_MODE_ONLINE_PRIMARY = 2;

  // Using OnDevice recognizer if specified application_domain supported
  // Otherwise, fallback to ONLINE_PRIMARY mode
  RECOGNIZER_MODE_ONDEVICE_PRIMARY = 3;

  // Using Online recognizer only
  RECOGNIZER_MODE_ONLINE_ONLY = 4;
}

message RecognitionResponse {
  reserved 1;
}
